### ISSUE TITLE
remove data

### ISSUE THREAD

**Issue by geraignacio** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#102]
### Description

Dear, how can I remove data that I do not want to appear in the report, for example the complete list of object addresses and I tried to delete lines in Get-AbrFgtFirewall but even so when generating the report all the data appears.

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues) before submitting this change request.

**Comment by alagoutte** [comment]
Hi,

do you have (re) import-module with -force after change ?

I known if is not possible for the moment for custom (option) each sub chapiter @tpcarman

**Comment by msoukhomlinov** [comment]
@geraignacio , if you want to exclude firewall address objects from the report, you can:
In "Get-AbrFgtFirewall.ps1" change "if ($Address -and $InfoLevel.Firewall -ge 1) {" to "if ($Address -and $InfoLevel.Firewall -ge 2) {"

**Comment by alagoutte** [comment]
> thanks and another question in case an authentication token is required, can it be added?

use API Token ? and not login/password ?

**Comment by geraignacio** [comment]
is MFA with fortitoken

**Comment by alagoutte** [comment]
> is MFA with fortitoken

Ok, you need to modify Public/Invoke....ps1 file for add -token_prompt on Connect-FGT function 

As build report Fortinet FortiGate use PowerFGT

**Comment by geraignacio** [comment]
I added what you told me but it doesn't ask me for the token
Connect-FGT -Server $System -Credential $Credential  -token_prompt
-SkipCertificateCheck -Port $Options.Port -vdom $Options.vdom | Out-Null

**Comment by geraignacio** [comment]
same error

ADVERTENCIA: [ 12:56:25:452 ] [ Document ] - Two-factor Authentication is
needed (use -token_code XXXXXX or -token_prompt)
New-AsBuiltReport : Not Connected. Connect to the Fortigate with Connect-FGT
En línea: 1 Carácter: 1
+ New-AsBuiltReport -Report Fortinet.FortiGate -Target 172.16.1.2 -User ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error],
WriteErrorException
    + FullyQualifiedErrorId :
Microsoft.PowerShell.Commands.WriteErrorException,New-AsBuiltReport

PS C:\WINDOWS\system32>

**Comment by alagoutte** [comment]
Sorry, never try with MFA

**Comment by geraignacio** [comment]
Ok, thank you very much for your time and help.
