### ISSUE TITLE
Feature request - Add the possibility to realize same export for a VDOM

### ISSUE THREAD

**Issue by rhumbert54** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#20]
Hi,

In some case, we use VDOM to split customers or data. If we have 10 or 1000 vdoms, data to collect could be consequent and it could be appreciate to have the possibility to filter to a VDOM name.

How ?
Add an option -vdom VDOMNAME

Best regards
Renaud HUMBERT

**Comment by alagoutte** [comment]
Hi Renaud,

Yes, it is planned to add on next release with [Options ](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#options)Parameter

**Comment by rhumbert54** [comment]
Hi Alexis,

Thanks a lot 😊

Cordialement,
Renaud HUMBERT
Support Technique Client TSR
[picto mail]
***@***.******@***.***>
[picto tel]
0383988930
[picto map]
Agence et Datacenters de Nancy
 ***@***.*** ***@***.***  [NSE 7] ***@***.***
***@***.***
***@***.***<https://www.adista.fr/communique-presse/adista-signe-laccord-dacquisition-de-waycom/>

***@***.***<https://www.adista.fr/>
***@***.***<https://twitter.com/adistafrance>
***@***.***<https://www.youtube.com/user/adistafrance>
***@***.***<https://fr.linkedin.com/company/adista-rmi>
***@***.***<https://www.facebook.com/adistafrance>




De : Alexis La Goutte ***@***.***>
Envoyé : vendredi 16 décembre 2022 10:31
À : AsBuiltReport/AsBuiltReport.Fortinet.FortiGate ***@***.***>
Cc : Renaud HUMBERT ***@***.***>; Author ***@***.***>
Objet : Re: [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate] Feature request - Add the possibility to realize same export for a VDOM (Issue #20)

ATTENTION : Ce courriel provient de l'extérieur du groupe ADISTA. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes à moins de connaître l'expéditeur et de savoir que le contenu est sûr.

________________________________


Hi Renaud,

Yes, it is planned to add on next release with Options <https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAsBuiltReport%2FAsBuiltReport.Fortinet.FortiGate%23options&data=05%7C01%7Crhumbert%40adista.fr%7Cdc98899209c54f78c6c608dadf484ee6%7C61b7c6667f1f45b5b4aefe7373641f03%7C0%7C0%7C638067798908737745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YVls2ojqoNMwr2nUVHb2PsQ0Iu34C0pyKnIQDFTarmk%3D&reserved=0> Parameter

**Comment by ahmadswailemCMC** [comment]
I totally agree, this would be a great addition.
Hope to see it soon, **Good luck and thank in advance.**

**Comment by alagoutte** [comment]
> I totally agree, this would be a great addition. Hope to see it soon, **Good luck and thanks in advance.**

Yes, it is always planned for next release (on next week/month ^^)
