### ISSUE TITLE
Feature request - VPN extraction

### ISSUE THREAD

**Issue by rhumbert54** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#21]
Hi,

**Is your feature request related to a problem? Please describe.**
There is no relation to a problem. It's just a suggestion to take more information

**Describe the solution you'd like**
add 2 Chapters
1/ VPN SSL (it is activate ? listen port ? IP access filtering ? dns and suffix ? authentication timeout and certificate)
2/ VPN IPSEC (phase 1 and phase 2 resume per tunnel)

**Describe alternatives you've considered**
A simple export from vpn ipsec phase1-interface and phase2-interface (mode tunnel is depreciate)  and grep to delete ENC psk and only specify if psk or certificate
A simple export from vpn ssl settings and grep to delete some information

Best regards
Renaud HUMBERT

**Comment by alagoutte** [comment]
Hi Renaud,

For VPN SSL, do you have the list of parameter do you want ? (from cli conf)
it will be not i on next release because i need to add Get function for VPN SSL on PowerFGT

for VPN IPsec, it will be more easy (Get function are already available) and i will be also possible to display PSK (i will make an option for this)

from your feedback, we need to display this

phase1-interface
```
       set interface xxx
        set ip-version x
        set ike-version x
        set local-gw xxx
        set keylife xxx
        set authmethod xxx
        set mode xxx
        set peertype any
        set mode-cfg xxx
        set proposal xxx
        set localid xxx
        set dpd xxx
        set dhgrp xxx
        set xauthtype xxx
        set nattraversal xxx
        set rekey xxx
        set remote-gw xx
```

phase2-interface
```
       set phase1name xxx
        set proposal xxx
        set dhgrp xxx
        set replay xxx
        set keepalive xxx
        set auto-negotiate xxx
        set keylife-type xxx
        set src-addr-type xxx
        set dst-addr-type xxx
        set keylifeseconds xxx
        set src-name xxx
        set dst-name xxx
	set src-subnet xxx
	set dst-subnet xxx
```

**Comment by rhumbert54** [comment]
Hi Alexis,

I think this parameters are interesting :
Idle-timeout
Auth-timeout
Force-two-factor-auth
Tunnel-ip-pools
Dns-suffix
Dns-server1
Dns-server2
Port
Source-address

Cordialement,
Renaud HUMBERT
Support Technique Client TSR
[picto mail]
***@***.******@***.***>
[picto tel]
0383988930
[picto map]
Agence et Datacenters de Nancy
 ***@***.*** ***@***.***  [NSE 7] ***@***.***
***@***.***
***@***.***<https://www.adista.fr/communique-presse/adista-signe-laccord-dacquisition-de-waycom/>

***@***.***<https://www.adista.fr/>
***@***.***<https://twitter.com/adistafrance>
***@***.***<https://www.youtube.com/user/adistafrance>
***@***.***<https://fr.linkedin.com/company/adista-rmi>
***@***.***<https://www.facebook.com/adistafrance>




De : Alexis La Goutte ***@***.***>
Envoyé : vendredi 16 décembre 2022 21:47
À : AsBuiltReport/AsBuiltReport.Fortinet.FortiGate ***@***.***>
Cc : Renaud HUMBERT ***@***.***>; Author ***@***.***>
Objet : Re: [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate] Feature request - VPN extraction (Issue #21)

ATTENTION : Ce courriel provient de l'extérieur du groupe ADISTA. Ne cliquez pas sur les liens ou n'ouvrez pas les pièces jointes à moins de connaître l'expéditeur et de savoir que le contenu est sûr.

________________________________


Hi Renaud,

For VPN SSL, do you have the list of parameter do you want ? (from cli conf)
it will be not i on next release because i need to add Get function for VPN SSL on PowerFGT

for VPN IPsec, it will be more easy (Get function are already available) and i will be also possible to display PSK (i will make an option for this)

from your feedback, we need to display this

phase1-interface

       set interface xxx



        set ip-version x



        set ike-version x



        set local-gw xxx



        set keylife xxx



        set authmethod xxx



        set mode xxx



        set peertype any



        set mode-cfg xxx



        set proposal xxx



        set localid xxx



        set dpd xxx



        set dhgrp xxx



        set xauthtype xxx



        set nattraversal xxx



        set rekey xxx



        set remote-gw xx



phase2-interface

       set phase1name xxx



        set proposal xxx



        set dhgrp xxx



        set replay xxx



        set keepalive xxx



        set auto-negotiate xxx



        set keylife-type xxx



        set src-addr-type xxx



        set dst-addr-type xxx



        set keylifeseconds xxx



        set src-name xxx



        set dst-name xxx



        set src-subnet xxx



        set dst-subnet xxx



-

**Comment by RantMaster** [comment]
Would it be possible to get a updated release with this feature #26 in it?

**Comment by alagoutte** [comment]
> Would it be possible to get a updated release with this feature #26 in it?

Hi @RantMaster, i want to add more feature before (VPN SSL and enhance User Part) but i hope for very soon !
