### ISSUE TITLE
Policy Table driven by Interface

### ISSUE THREAD

**Issue by rkirmis** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#22]
**Is your feature request related to a problem? Please describe.**
It is only a feature request

**Describe the solution you'd like**
It would be nice, if the policy table in the report looks like the view in the gui of fortinet.
There is obviously no sorting in the report, since all the interfaces are mixed up there. 
I would like a display like the Fortinet web interface with the option Interface pair view

**Comment by alagoutte** [comment]
hi @rkirmis,

yes, it is possible with 2 (foreach) loop, it will look for add on future release

**Comment by alagoutte** [comment]
Adding by Sequence for the moment https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/pull/62

i will see after for support also this case

**Comment by alagoutte** [comment]
@tpcarman you can close this issue
