### ISSUE TITLE
Trusted Hosts delete 0.0.0.0/0

### ISSUE THREAD

**Issue by LoicLys** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#39]
### Bug description

In the report, in the System -Admin section, there are multiples of 0 in the Trusted Hosts column. 

While there are trusted set up

### Command-line input

New-AsBuiltReport -Report Fortinet.FortiGate -Target 192.168.15.1 -Username Loic -Password Endurable7-Brought-Unearth -Format Html,Word -ReportConfigFilePath 'C:\Users\LoïcLysinskiSIPsa\Desktop\AsBuiltReport.Fortinet.FortiGate.json' -OutputFolderPath 'C:\Users\LoïcLysinskiSIPsa\Desktop' -Timestamp

### Steps to reproduce

1. delete 0.0.0.0/0 

### Expected behaviour

deletion of unnecessary 0.0.0.0

### Screenshots

![2023-07-28 09_25_56-Window](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/140793232/fcd8ee52-5e31-4118-a4fc-2ceabd09040a)

### Operating System

WIndows 10

### PowerShell Version

5.1.19041.3031

### PowerShell Modules

Name                             Version
----                             -------
AsBuiltReport.Core               1.3.0
AsBuiltReport.Fortinet.FortiGate 0.2.0
PowerFGT                         0.7.0
PScribo                          0.10.0

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues) before submitting this bug report.

**Comment by alagoutte** [comment]
What do you want to display when there is only 0.0.0.0/0 ?

**Comment by LoicLys** [comment]
Just once when there's no trust
