### ISSUE TITLE
Add the "Ref." column

### ISSUE THREAD

**Issue by Boyl4n** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#52]
### Description

Hi,

It would be interesting to add the "Ref." column.
This will at least allow you to check whether an object is used or not.

Great job.
++

### Before submitting

- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this change request.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues) before submitting this change request.

**Comment by alagoutte** [comment]
Yes, it is a missing feature but need to add Ref before on PowerFGT (with &with_meta=1) before (Already ask -> https://github.com/FortiPower/PowerFGT/discussions/223
