### ISSUE TITLE
Empty value when firewall policy use ISDB

### ISSUE THREAD

**Issue by rhumbert54** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#70]
### Bug description

Hi,

When i generate a doc for a FortiGate using Fortinet ISDB, every rule using these objets appear with empty value "" in the document.
![image](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/110679857/8ed78fae-3e4b-4dae-8ae6-022cd97b534a)

Regards
Renaud HUMBERT

### Command-line input

-

### Steps to reproduce

Use ISDB on firewall policy

### Expected behaviour

get the ISDB name apply on

### Screenshots

![image](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/110679857/2f278dec-020b-4f72-8979-fd23e50aa546)

### Operating System

-

### PowerShell Version

7

### PowerShell Modules

-

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues) before submitting this bug report.

**Comment by alagoutte** [comment]
Hi @rhumbert54 

Thanks, i confirm, i will work on a fix !
