### ISSUE TITLE
[BUG] No policy report generate

### ISSUE THREAD

**Issue by rhumbert54** [AsBuiltReport/AsBuiltReport.Fortinet.FortiGate#74]
### Bug description

Hi,

When we generate documentation for VDOM firewall, the policy chapter is empty.

Chapter 1.5.5 is empty, 1.5.4 is ok. 

I tried on two firewalls (with vdoms) and the issue is the same.
If i generate one on normal firewall (without vdom), it's ok.

Could you take a look please ?

Best regards
Renaud HUMBERT

### Command-line input

-

### Steps to reproduce

vdom firewall

### Expected behaviour

-

### Screenshots

![image](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/110679857/43ff0548-fcac-427d-b04d-2e38db2ef3bf)
![image](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/110679857/9239ea15-bcc2-4acf-97f4-c434c6d147b0)
![image](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/assets/110679857/1cc1b96a-4e58-4b9b-89f3-726583fa1125)

### Operating System

2022 server

### PowerShell Version

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.2400
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2400
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### PowerShell Modules

Modules : 
Script     1.4.0      AsBuiltReport.Core
Script     0.3.0      AsBuiltReport.Fortinet.FortiGate
Script     0.8.1      PowerFGT
Script     0.10.0     PScribo

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://www.asbuiltreport.com/about/contributing/#reporting-issues-and-bugs).
- [X] I have read [the documentation](https://www.asbuiltreport.com/user-guide/new-asbuiltconfig), and referred to the [known issues](https://www.asbuiltreport.com/user-guide/known-issues/) before submitting this bug report.
- [X] I have checked for previously opened & closed [issues](https://github.com/AsBuiltReport/AsBuiltReport.Fortinet.FortiGate/issues) before submitting this bug report.

**Comment by alagoutte** [comment]
Hi @rhumbert54 

Can you check you have a PolicyLayout Settings on  AsBuiltReport.Fortinet.FortiGate.json ? (new feature of 0.3.0)

**Comment by rhumbert54** [comment]
Yes, you're right.

I used always the same .json file that i edit for. So this options wasn't in my file.

I tried to add it and generate a new vdom report and it works.

My bad, Sorry about this mistake.

I update my documentation.

Best regards

**Comment by alagoutte** [comment]
> Yes, you're right.
> 
> I used always the same .json file that i edit for. So this options wasn't in my file.
> 
> I tried to add it and generate a new vdom report and it works.
> 
> My bad, Sorry about this mistake.
> 
> I update my documentation.
> 
> Best regards

de rien :)
